# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Missouri Valley Ambulance
tagline:
description:      Ramblings of a Apple tech geek

author:
  name:           'Morgan Speck'
  url:            https://twitter.com/morganpspeck

paginate:         5
