# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Missouri Valley Ambulance
tagline:
description:      Ramblings of a Apple tech geek
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Morgan Speck'
  url:            https://twitter.com/morganpspeck

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
