# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MISSOURI VALLEY AMBULANCE
title2:           Test
tagline:
description:      The utterly inane ramblings of surely a moron. For only a fool would make a blog in this day and age.
url:              http://missourivalleyambulance.com
baseurl:          /
author:
  name:           'Morgan Speck'
  url:            https://twitter.com/morganspeck

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
