# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
image:            favicon.ico
title:            MISSOURI VALLEY AMBULANCE
tagline:
description:      The ramblings of surely a moron.
url:              http://missourivalleyambulance.com
baseurl:          /

author:
  name:           'Morgan speck'
  url:            https://twitter.com/morganspeck

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
